import adobe from './adobe.svg'
import css from './css.svg'
import email from './email.svg'
import javascript from './javascript.svg'
import linkedin from './linkedin.svg'
import moon from './moon.svg'
import phone from './phone.svg'
import react from './react.svg'
