import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Grid from '@mui/material/Grid'
import { makeStyles } from '@mui/styles'
import Link from 'next/link'

export default function Home() {
  const useStyles = makeStyles({
    root: {
      background: 'grey',
      height: '100%',
      width: '100%',
    },
    container: {
      // display: 'flex',
      // flexDirection: 'column',
      // background: 'purple',
    },
  })
  const classes = useStyles()
  return (
    <Grid
      container
      className={classes.root}
      justifyContent="center"
      alignItems="center">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        className={classes.container}
        alignItems="center"
        direction="column"
        gap={4}>
        <Grid item>
          <Link href="projects">PROJECTS</Link>
        </Grid>
        <Grid item>
          <Link href="skills">SKILLS</Link>
        </Grid>
        <Grid item>
          <Link href="aboutMe">ABOUT ME</Link>
        </Grid>
        <Grid item>
          <Link href="contactMe">CONTACT ME</Link>
        </Grid>
      </Grid>
    </Grid>
  )
}
